import type { Metadata } from "next";

import { auth } from "@/auth";
import PublicHeader from "@/components/layouts/PublicHeader";

export const metadata: Metadata = {
  title: ".Blog",
  description: "Generated by create next app",
};

export default async function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const session = await auth();

  return (
    <div>
      <PublicHeader session={session}/>
      {children}
    </div>
  );
}
